Update CI.yml

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -25,6 +25,15 @@ jobs:
       - name: Run Tests and Generate Result File
         run: npm test
 
+      - name: Verify result.json
+        run: |
+          if [ ! -f result.json ]; then
+            echo "result.json not found!"
+            exit 1
+          fi
+          cat result.json
+
+
       - name: Send Test Results to Qase
         run: |
           curl -X POST https://api.qase.io/v1/result/LP/run/1 \
